// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_vonBT_TMBExports
#include <TMB.hpp>
#include "VonBTv1.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "VonBTv1") {
    return VonBTv1(this);
  } else {
    Rf_error("Unknown model.");
  }
  return 0;
}
